* My personal Emacs configuration
My Spacemacs configuration is based on [[https://github.com/zilongshanren/spacemacs-private][zilongshanren]].

** Installation on Mac
1. Install [[https://github.com/railwaycat/homebrew-emacsmacport][Emacs-mac]].

#+BEGIN_SRC shell
brew tap railwaycat/emacsmacport
brew install emacs-mac --with-spacemacs-icon --HEAD --with-gnutls
#+END_SRC

Note: ~--with-gnutls~ is used to support ssl

Put emacs-mac in the Applications folder by using ~brew linkapps emacs-mac~.

2. Install spacemacs: ~git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d~
3. Install Ubuntu Mono font
4. Solution to incoming network connection:

Codesign your Emacs.app

Instructions over [[http://apple.stackexchange.com/questions/3271/how-to-get-rid-of-firewall-accept-incoming-connections-dialog/170566][here]].

Sample shell command:
#+BEGIN_SRC shell
codesign --deep --force --verbose --sign ztlevi /usr/local/Cellar/emacs-mac/HEAD-7403929/Emacs.app~
#+END_SRC

** What's the highlight of this configuration
1. It's a highly customize optimized Spacemacs configuration, it's relied on the develop branch of the officially Spacemacs.
2. I prefer to the =Ivy= completion interface, so I removed many helm related packages but keep the =helm-ag= package. The =counsel-ag= counterpart is not powerful as =helm-ag=.
3. I also removed some packages I don't have any chance to use. The complete lists are in the exclude section of the =init.el= file.
4. I also exclude the =Spaceline= package, cause it's easy to frozen the Emacs with this package enabled. So I create my own mode line configuration based =Spaceline=.
5. The =Swiper= package sometimes frozen the Emacs UI only when you split the window. You could use `pkill -SIGUSR2 -i emacs` command line to rescue.

** Happing Hacking
