* My personal Emacs configuration
My Spacemacs configuration is based on [[https://github.com/zilongshanren/spacemacs-private][zilongshanren]].

** Installation on Mac
1. Install [[https://github.com/railwaycat/homebrew-emacsmacport][Emacs-mac]]. 

```
brew tap railwaycat/emacsmacport
brew install emacs-mac --with-spacemacs-icon --HEAD --with-gnutls
```
Note: ~--with-gnutls~ is used to support ssl

Make a symbolic alias, e.g. ~ln -s /usr/local/Cellar/emacs-mac/emacs-25.2-rc1-mac-6.2/Emacs.app /Applications/Emacs.app~ 
2. Install spacemacs: ~git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d~
3. Install Ubuntu Mono font

** What's the highlight of this configuration
1. It's a highly customize optimized Spacemacs configuration, it's relied on the develop branch of the officially Spacemacs.
2. I prefer to the =Ivy= completion interface, so I removed many helm related packages but keep the =helm-ag= package. The =counsel-ag= counterpart is not powerful as =helm-ag=.
3. I also removed some packages I don't have any chance to use. The complete lists are in the exclude section of the =init.el= file.
4. I also exclude the =Spaceline= package, cause it's easy to frozen the Emacs with this package enabled. So I create my own mode line configuration based =Spaceline=.
5. The =Swiper= package sometimes frozen the Emacs UI only when you split the window. You could use `pkill -SIGUSR2 -i emacs` command line to rescue.

** Happing Hacking
